#!/bin/sh

set -eu

echo "/* THIS FILE IS AUTO GENERATED BY snmp.sh */"

#
# collect power socket states
#

for g in 1 2 3; do
	for p in 1 2 3 4 5 6 7 8; do
		stat=$(snmp get -Oqv gude$g .iso.org.dod.internet.private.enterprises.28507.1.1.2.2.1.3.$p)
		name=$(snmp get -Oqv gude$g .iso.org.dod.internet.private.enterprises.28507.1.1.2.2.1.2.$p)

		echo "#g${g}p${p}::before { content: \"$name\"; }"
		if [ $stat -eq 1 ]; then
			echo "#g${g}p${p} { background-color: #73d216; }"
		else
			echo "#g${g}p${p} { background-color: #cc0000; }"
		fi
	done
	echo
done

#
# collect interface information
#

for ot in 1 2 3 4 6 7 10 11 14 15 21 26 27 28 29 31 32; do
	for i in 1 2 3 4 5 6 7 8 9; do
		name=$(snmp get -r 0 -Oqv ot$ot .iso.org.dod.internet.mgmt.mib_2.ifMIB.ifMIBObjects.ifXTable.ifXEntry.ifName.$i) || break
		speed=$(snmp get -r 0 -Oqv ot$ot .iso.org.dod.internet.mgmt.mib_2.ifMIB.ifMIBObjects.ifXTable.ifXEntry.ifHighSpeed.$i) || break

		if [ "$name" = "No Such Object available on this agent at this OID" ]; then
			break 1
		fi

		if [ "$name" = "enc0" -o "$name" = "lo0" -o "$name" = "pflog0" ]; then
			echo "#ot${ot}i${i} { display: none; }"
			continue
		fi

		echo "#ot${ot}i${i}::before { content: \"$name\"; }"

		if [ $speed -eq 0 ]; then
			echo "#ot${ot}i${i} { background-color: #d3d7cf; }"
		else
			echo "#ot${ot}i${i} { background-color: #73d216; }"
		fi
	done
	echo
done
